// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkOBZwQ22B_d5AdJZidTL0va6EAnFRtn4',
    appId: '1:237332047836:web:b65f51fcffbfa6ddb29119',
    messagingSenderId: '237332047836',
    projectId: 't1d-project-70bfa',
    authDomain: 't1d-project-70bfa.firebaseapp.com',
    storageBucket: 't1d-project-70bfa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmni4WpqMPd9mC9XYR_FEv227Lcq8oz-Q',
    appId: '1:237332047836:android:e8b2b1669fd50885b29119',
    messagingSenderId: '237332047836',
    projectId: 't1d-project-70bfa',
    storageBucket: 't1d-project-70bfa.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXjvcOU5agkZ6YkYRzX8bObM8P5S65McA',
    appId: '1:237332047836:ios:1ff996eb34467bacb29119',
    messagingSenderId: '237332047836',
    projectId: 't1d-project-70bfa',
    storageBucket: 't1d-project-70bfa.firebasestorage.app',
    iosClientId: '237332047836-3o1or63a41qtdmoqfqfdn42hio0l2q6n.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXjvcOU5agkZ6YkYRzX8bObM8P5S65McA',
    appId: '1:237332047836:ios:1ff996eb34467bacb29119',
    messagingSenderId: '237332047836',
    projectId: 't1d-project-70bfa',
    storageBucket: 't1d-project-70bfa.firebasestorage.app',
    iosClientId: '237332047836-3o1or63a41qtdmoqfqfdn42hio0l2q6n.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkOBZwQ22B_d5AdJZidTL0va6EAnFRtn4',
    appId: '1:237332047836:web:9d0d304d5ce8c752b29119',
    messagingSenderId: '237332047836',
    projectId: 't1d-project-70bfa',
    authDomain: 't1d-project-70bfa.firebaseapp.com',
    storageBucket: 't1d-project-70bfa.firebasestorage.app',
  );

}